$target_text = '<p>内容深度撰写中，稍后由 AI 接入更新\.\.\.</p>'

$qx_html = '<h2>为什么学会正确导入 Quantumult X 订阅链接至关重要？</h2><p>在如今复杂的网络环境中，Quantumult X（俗称圈X）凭借其强大的策略组分流、脚本重写规则以及高度可定制化的特性，成为了 iOS 用户心目中的“翻墙神器”。然而，对于很多新手来说，购买了像<strong>微风网络</strong>、<strong>暮光云</strong>这样优质的机场服务后，如何将机场订阅链接正确导入 Quantumult X 却成了第一道难关。正确导入订阅不仅意味着您能顺利连接到国际网络，更决定了您能否充分发挥这些顶级节点（如<strong>飞猫云</strong>的高速专线）的最佳性能。如果导入姿势不对，可能会导致节点刷新失败、策略组混乱，甚至完全无法联网。因此，掌握这一核心技能，是畅享自由网络的基石。</p><h3>第一步：获取优质机场的 Quantumult X 订阅链接</h3><p>在开始导入之前，您需要拥有一个稳定可靠的机场服务。我们强烈推荐使用<strong>大佬云</strong>或者<strong>Firefly</strong>等提供原生 Quantumult X 订阅格式的机场。登录您的机场后台面板，在“仪表盘”或“订阅中心”找到“一键订阅”按钮，点击后选择“复制 Quantumult X 订阅链接”。需要注意的是，由于圈X的配置要求较高，部分老旧机场可能只提供通用转换链接，而像<strong>闪跃</strong>和<strong>无忧</strong>这类新兴的高端机场，通常会直接提供兼容性极佳的专属订阅链接。确保复制的是专门为圈X准备的链接。</p><h3>第二步：打开 Quantumult X 并进入配置界面</h3><p>在您的 iPhone 或 iPad 上打开 Quantumult X 应用程序。点击屏幕右下角的“风车”图标（即设置按钮），进入主要设置页面。在这里，您可以看到各种高级选项，包括节点、分流规则、重写等。向下滚动，找到“节点（Server）”模块，点击“引用（Quotes）”或“订阅（Subscriptions）”选项。这一步是我们将<strong>跨界</strong>等高端节点引入本地客户端的关键入口。</p><h3>第三步：添加并保存订阅链接</h3><p>在节点订阅管理页面，点击右上角的“+”号来添加新的订阅源。系统会弹出一个窗口要求您输入标签（Label）和资源路径（Resource）。在标签栏，您可以随意命名，例如“微风网络”或“飞猫云-专线”。在资源路径栏，粘贴您刚才在机场后台复制的 Quantumult X 订阅链接。为了保证节点更新的及时性，建议勾选“自动更新”选项，这样当<strong>暮光云</strong>等机场增加新节点或优化线路时，您的客户端能自动同步最新的节点信息。确认无误后，点击右上角的“保存”。</p><h3>第四步：更新订阅并测试连接</h3><p>保存完毕后，回到节点订阅列表，您会看到刚刚添加的订阅源。向左滑动该条目，或者点击条目进入详情页，选择“更新（Update）”。此时，Quantumult X 会从机场服务器拉取节点列表，如果您的网络环境正常且订阅链接有效，几秒钟后屏幕上会提示更新成功，并显示解析出的节点数量。回到软件首页，长按右下角的风车图标，选择一个节点（比如来自<strong>大佬云</strong>的香港节点），然后点击顶部中心的开关以开启 VPN。您可以打开浏览器访问被墙的网站，测试是否连接成功。</p><h3>常见问题与注意事项</h3><p>在导入过程中，您可能会遇到一些小问题。例如，提示“解析失败”，这通常是因为网络限制导致无法直接访问订阅服务器。这时候您可以尝试在 Wi-Fi 和蜂窝网络之间切换，或者使用支持订阅代理的工具。另外，如果您同时使用了多个机场，比如主力使用<strong>Firefly</strong>，备用使用<strong>闪跃</strong>或<strong>无忧</strong>，建议为每个机场设置不同的标签和策略组，以便于管理和切换。合理利用 Quantumult X 的分流功能，能让您在访问国内网站时直连，访问国际网站时走<strong>跨界</strong>等优质机场的代理，既节省流量又提升速度。</p><p>总之，熟练掌握 Quantumult X 的订阅导入方法，不仅能让您快速接入世界，更是探索这跨界网络工具强大潜力的起点。只要按部就班地操作，即便小白也能轻松搞定。</p>'

$sr_html = '<h2>为什么学会正确导入 Shadowrocket 订阅链接至关重要？</h2><p>Shadowrocket（被广大用户亲切地称为“小火箭”）是 iOS 平台上最普及、最容易上手的代理客户端之一。无论是对于刚接触科学上网的新手，还是追求稳定高效的老玩家，小火箭都是不可或缺的工具。正确地将机场订阅链接导入 Shadowrocket，是连接世界的第一步。如果您使用的是<strong>微风网络</strong>或<strong>暮光云</strong>这样注重用户体验的高端机场，正确的导入方法能确保您获取最完整的节点列表和最新的路由规则，避免因为格式错误导致节点信息丢失、无法连接，甚至泄露真实 IP。掌握导入技巧，能让您充分利用<strong>飞猫云</strong>等机场提供的高速带宽，享受无缝的网络体验。</p><h3>第一步：获取 Shadowrocket 专属订阅链接</h3><p>首先，您需要登录您的机场用户中心。无论您选择的是老牌求稳的<strong>大佬云</strong>，还是近期备受好评的<strong>Firefly</strong>，在它们的后台主页通常都能找到非常醒目的“一键订阅”区域。点击该区域，在弹出的菜单中选择“复制 Shadowrocket 订阅链接”或“一键导入 Shadowrocket”。如今，像<strong>闪跃</strong>和<strong>无忧</strong>等现代化机场，已经完美适配了小火箭的一键导入功能（基于 shadowrocket:// 协议）。如果您在手机上直接操作，点击“一键导入”会直接唤醒 Shadowrocket 应用；如果是复制链接，则需要进行手动添加。</p><h3>第二步：手动添加订阅链接（若一键导入失败）</h3><p>如果在第一步中一键导入未能成功唤醒 APP，不用担心，我们可以手动添加。打开 Shadowrocket 应用程序，点击首页右上角的“+”号。在弹出的“添加节点”页面中，最顶部有一个“类型（Type）”选项，点击它并将其更改为“Subscribe（订阅）”。接着，在“URL”输入框中，粘贴您刚刚复制的订阅链接。在“备注（Remarks）”栏，您可以填写机场的名称，例如“微风网络-VIP线路”或“跨界-全节点”，以方便日后区分。填写完毕后，点击右上角的“完成（Done）”或“保存”。</p><h3>第三步：更新订阅与全局路由设置</h3><p>返回到小火箭的主界面，您会在“服务器（Servers）”列表中看到刚刚添加的订阅源。为了获取节点，请在屏幕上向下轻扫刷新，或者点击订阅源右侧的“更新”按钮。几秒钟后，当看到节点列表全部加载出来，就说明导入成功了。接下来，非常关键的一步是设置全局路由（Global Routing）。在首页底部的选项卡中找到“全局路由”，通常建议选择“配置（Config）”或“代理（Proxy）”。“配置”模式会根据规则自动判断是否走代理，是日常使用的最佳选择；如果您在使用<strong>暮光云</strong>等提供全代理服务的场景下，也可以临时切换为“代理”模式。</p><h3>第四步：连通性测试与愉快冲浪</h3><p>一切准备就绪后，回到首页。在节点列表中选择一个延迟较低的节点（点击节点名称，左侧会出现一个小黄点表示已选中）。然后拨动屏幕上方巨大的开关按钮开启 VPN。首次使用时，iOS 会弹出一个系统提示，要求允许添加 VPN 配置，请验证您的指纹或面容ID以授权。连接成功后，状态栏会出现 VPN 图标。您可以点击节点列表底部的“连通性测试”来查看各个节点的实际延迟，确保<strong>飞猫云</strong>或<strong>大佬云</strong>的优质节点运行在最佳状态。</p><h3>常见问题与自动更新设置</h3><p>为了保持节点的时效性，尤其是当<strong>Firefly</strong>、<strong>闪跃</strong>、<strong>无忧</strong>等机场进行服务器维护或线路扩容时，设置自动更新非常必要。点击底部的“设置（Settings）”，进入“服务器订阅”，打开“打开时更新（Update on open）”和“自动后台更新（Auto update）”开关。这样，您的小火箭就会始终保持与机场后台的数据同步。如果遇到更新失败的情况，可以检查网络连接，或者尝试将蜂窝网络切换到 Wi-Fi，必要时联系<strong>跨界</strong>等机场的客服获取备用订阅链接。掌握这些，您的科学上网之旅将畅通无阻。</p>'

$sb_html = '<h2>为什么学会正确导入 sing-box 订阅链接至关重要？</h2><p>近年来，sing-box 作为一个新兴的通用代理平台，以其跨平台、轻量级且性能卓越的特点，迅速在极客圈和高级用户中风靡。与传统的客户端不同，sing-box 采用了更现代化的底层架构，支持丰富的协议和极其灵活的规则集。然而，正是因为其强大的可定制性，导入订阅链接的过程相比其他工具稍显复杂。正确地将订阅导入 sing-box，能够让您充分挖掘像<strong>微风网络</strong>、<strong>暮光云</strong>等顶级机场的潜力，实现更精准的智能分流和更稳定的连接体验。如果您想在多设备上获得一致且流畅的网络环境，并让<strong>飞猫云</strong>等优质线路发挥出极致性能，掌握 sing-box 的订阅导入方法是必修课。</p><h3>第一步：确认机场是否原生支持 sing-box 格式</h3><p>由于 sing-box 使用的是基于 JSON 的配置格式，并非所有机场都原生提供此类链接。在导入前，请登录您的机场后台，查看订阅中心是否有专门的“sing-box 订阅链接”。目前，像<strong>大佬云</strong>、<strong>Firefly</strong>等注重技术前沿的机场，以及<strong>闪跃</strong>和<strong>无忧</strong>等新锐服务商，已经开始提供对 sing-box 的原生支持。如果您的机场没有直接提供，您可能需要借助第三方的订阅转换工具（如 Subconverter），将通用的 Clash 或 V2Ray 订阅链接转换为 sing-box 兼容的格式。这对于体验<strong>跨界</strong>等服务来说是前置准备。</p><h3>第二步：下载并安装 sing-box 客户端</h3><p>sing-box 支持 Windows、macOS、Linux、iOS 和 Android 多个平台。请前往其官方 GitHub 发布页面或应用商店（如 Apple App Store 或 Google Play）下载对应您设备的最新版本。安装完成后打开软件，您会发现其界面十分简洁，初次使用甚至显得有些“硬核”。这正是因为 sing-box 把核心精力放在了底层网络性能的优化上，让<strong>微风网络</strong>等高速节点能够无损耗地传递数据。</p><h3>第三步：创建新的配置文件（Profile）</h3><p>在 sing-box 的主界面中，找到配置（Profiles）选项卡，点击添加（Add）或新建（New）按钮来创建一个新的配置文件。在配置类型中，选择“Remote（远程）”或者“Subscription（订阅）”。在弹出的设置面板中，输入配置文件的名称（如“暮光云-主节点”）。在 URL 字段中，粘贴您从机场后台获取的或者经过转换得到的 sing-box 专用订阅链接。为了确保您能随时获取<strong>飞猫云</strong>等机场新增的线路，建议在设置中配置好自动更新的时间间隔（例如每 24 小时更新一次）。</p><h3>第四步：保存并启动代理服务</h3><p>完成 URL 的填写后，保存配置文件。此时，软件会尝试从远程服务器下载完整的 JSON 配置文件并进行解析。如果在解析过程中报错，请仔细检查链接是否完整，或者转换工具的参数是否正确。一旦配置下载成功并被设为激活状态（Active），回到 Dashboard 或主控制页面，点击“启动（Start）”按钮。此时，sing-box 将接管您的网络流量。您可以在面板中查看实时的连接状态、延迟以及经过<strong>大佬云</strong>或<strong>Firefly</strong>等节点的数据吞吐量。</p><h3>进阶调优与常见问题解决</h3><p>sing-box 的真正魅力在于它的规则集（Rule Sets）和路由（Routing）配置。导入订阅后，您可能需要根据自己的需求，在配置文件中微调 DNS 设置或特定的分流规则，以确保国内流量直连，国外流量走<strong>闪跃</strong>或<strong>无忧</strong>的高速代理。如果遇到无法联网的问题，首先检查操作系统的代理设置是否已被正确接管；其次，查看 sing-box 的运行日志（Logs），日志中通常会详细记录是 DNS 解析失败，还是连接被拒绝。熟练使用 sing-box，将为您打开一扇通往自由且高度定制化网络世界的大门，让诸如<strong>跨界</strong>等各类机场服务在您的手中发挥出百分之百的实力。</p>'

$path_qx = 'c:\Users\USER\Desktop\BLOG\Github内容\Home\topic\tuijianjichang\faq\jichang-dingyue-lianjie-zenme-daoru-quantumultx.html'
$path_sr = 'c:\Users\USER\Desktop\BLOG\Github内容\Home\topic\tuijianjichang\faq\jichang-dingyue-lianjie-zenme-daoru-shadowrocket.html'
$path_sb = 'c:\Users\USER\Desktop\BLOG\Github内容\Home\topic\tuijianjichang\faq\jichang-dingyue-lianjie-zenme-daoru-sing-box.html'

(Get-Content $path_qx -Raw -Encoding UTF8) -replace $target_text, $qx_html | Set-Content $path_qx -Encoding UTF8
(Get-Content $path_sr -Raw -Encoding UTF8) -replace $target_text, $sr_html | Set-Content $path_sr -Encoding UTF8
(Get-Content $path_sb -Raw -Encoding UTF8) -replace $target_text, $sb_html | Set-Content $path_sb -Encoding UTF8
